  
  
CREATE TABLE comments (
  id int generated by default as identity (START WITH 1, INCREMENT BY 1),
  image_id int default NULL,
  text VARCHAR(256),
  PRIMARY KEY  (id)
) ;

#
# Table structure for table 'folders'
#

CREATE TABLE folders (
  id int generated by default as identity (START WITH 1, INCREMENT BY 1),
  folder VARCHAR(255) NOT NULL,
  hits int NOT NULL default 0,
  PRIMARY KEY  (id)
);

#
# Table structure for table 'images'
#

CREATE TABLE images (
  id int generated by default as identity (START WITH 1, INCREMENT BY 1),
  folderid int NOT NULL default 0,
  image VARCHAR(50) NOT NULL,
  hits int NOT NULL default 0,
  PRIMARY KEY  (id)
);


