<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
  <meta content="text/html; charset=${folder.textEncoding}"
 http-equiv="content-type">
  <title>${folder.title}</title>
  <link href="${folder.stylePath}" rel=stylesheet>
</head>
<body>

<a href="<c:url value='${folder.indexPage}'/>"> ${folder.title} </a> / (Image ${folder.imageNum}/${folder.totalImages})


<!-- Previous Slide -->
<c:if test="${!empty folder.previousPage}">
	<a href="<c:url value='${folder.previousPage}'/>">&lt;&lt;</a>
</c:if>

<!-- Next Slide -->
<c:if test="${!empty folder.nextPage}">
	<a href="<c:url value='${folder.nextPage}'/>">
	&gt;&gt;</a>
</c:if>

<center>
<table>
<tr>

<td>

<img src="${image.imagePath}" width="${image.imageWidth}" height="${image.imageHeight}" usemap="#imagemap"/>

  	<map name="imagemap">
  	<c:if test="${!empty folder.previousPage}"> 
  		<area shape="rect" coords="0,0,${image.imageWidth / 2},${image.imageHeight}" href="<c:url value='${folder.previousPage}'/>" />
  	</c:if> 
 	  <c:if test="${!empty folder.nextPage}">
 	  	<area shape="rect" coords="${image.imageWidth / 2},0,${image.imageWidth},${image.imageHeight}" href="<c:url value='${folder.nextPage}'/>" />
      </c:if> 
 	</map>  

</td>


</tr>

</table>


</center>
<a href="${folder.generatorurl}" target="_blank"><small>generated by ${folder.generator}</small></a>
</body>
</html>
