<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
  <meta content="text/html; charset=${folder.textEncoding}"
 http-equiv="content-type">
  <title>${folder.title}</title>
  <link href="${folder.stylePath}" rel=stylesheet>
</head>
<body>

${folder.title} 
<c:if test="${!empty folder.totalIndexes}">(${folder.indexNum}/${folder.totalIndexes})</c:if>



<c:if test="${!empty folder.totalIndexes}">

<select style="border: 0px none;" onchange="window.location.href = this.options[this.selectedIndex].value">
   
<c:forEach var="page" items="${folder.pageIndexes}">

   <option ${page.selected} value="${page.page}">Page ${page.number}</option>

</c:forEach>
   
   
   
</select> 


	<!-- Previous index -->
	<jg:if exists="${folder.previousIndexPage}">
		<a href="${folder.previousIndexPage}">
		&lt;&lt; </a>
	</jg:if>

	<!-- Next index -->
	<jg:if exists="${folder.nextIndexPage}">
		<a href="${folder.nextIndexPage}">
		&gt;&gt;</a>
	</jg:if>
</c:if>




<center>

<table>
<jg:rowiterator> 
	<tr>
	<jg:coliterator>
	
		<td>
	
		<a href="${image.closeupPath}">
			<img class="image" 
				src="${image.thumbPath}" 
				width="${image.thumbWidth}" 
				height="${image.thumbHeight}" 
		</a> 
		</td>
		
	</jg:coliterator>
	</tr>
</jg:rowiterator>
</table>		

</center>


<a href="${folder.generatorurl}" target="_blank"><small>generated by ${folder.generator}</small></a>
</body>
</html>
